#! /usr/bin/env bash

set -euo pipefail

log() {
  printf '%s\n' "$@"
} >&2

usage() {
  cat <<DOG
usage: $0 merged.csv
DOG
}

die() {
  local ex="${1:-1}"
  exit "$ex"
}

usage_and_die() { usage && die; }

main() {
  if (($# < 1)); then
    usage_and_die
  fi

  <"$1" sed 's/(Eastern Standard Time)/(EST)/g'
}

main "$@"
