#! /usr/bin/env bash

set -euo pipefail
current_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

log() {
  printf '%s\n' "$@"
} >&2

usage() {
  cat <<DOG
usage: $0 merged.csv assessment.xls
DOG
}

die() {
  local ex="${1:-1}"
  exit "$ex"
}

usage_and_die() { usage && die; }

main() {
  if (($# < 2)); then
    usage_and_die
  fi

  local csv="$1"
  local xls="$2"

  "$current_dir"/stat -a <"$csv"
  "$current_dir"/sakai_stat.py "$xls" "$csv"
}

main "$@"
