#! /usr/bin/env bash

set -euo pipefail

log() {
  printf '%s\n' "$@"
} >&2

usage() {
  cat <<DOG
usage: $0 [dupes|count]

Filters stdin to produce
  - all ids given no arguments (not deduplicated)
  - duplicate ids or count of attendees, given the appropriate argument
DOG
}

die() {
  local ex="${1:-1}"
  exit "$ex"
}

usage_and_die() { usage && die; }

ids() {
  sed '1d' | awk -F, '{print $1}'
}

dupes() {
  ids | uniq -c | awk '$1 > 1'
}

count() {
  ids | uniq | wc -l
}

main() {
  case $# in
    0) ids ;;
    1)
      case "$1" in
        dupes|count) "$1" ;;
        *) usage_and_die ;;
      esac
      ;;
    *) usage_and_die ;;
  esac
}

main "$@"
